version: "3.2"                    # Using version 3 docker-compose
services:
    kleinfelter:
        build: .
        network_mode: "bridge"
        container_name: kleinfelter
        restart: unless-stopped
        ports:
            # host-port:container-port
            - "127.0.0.1:4002:4002"
        volumes:
            - type: bind
              source: "."
              target: "/srv/jekyll"
        environment:
        - TZ

        command: jekyll serve --port 4002 -H 0.0.0.0 --watch --incremental
       #command: jekyll serve --port 4002 -H 192.168.8.10 --watch --incremental --verbose

